import { Injectable } from '@angular/core';
import {Foods} from 'src/app/shared/models/food'
@Injectable({
  providedIn: 'root'
})
export class FoodService {

  constructor() { }

  getAll():Foods[]
  {
    return[
      {
        id:1,
        name: 'Burger',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['Germany'],
        star: 4.5,
        imageUrl: '/assets/images/foods/food-1.jpg',
        tags:['Fastfood', 'Burger', 'Lunch'],
      },
      {
        id:2,
        name: 'Sandwich',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['England'],
        star: 4,
        imageUrl: '/assets/images/foods/food-2.jpg',
        tags:['Fastfood', 'Sandwich', 'Lunch'],
      },
      {
        id:3,
        name: 'Pizza',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['Italy'],
        star: 4,
        imageUrl: '/assets/images/foods/food-3.jpg',
        tags:['Fastfood', 'Pizza', 'Lunch'],
      },
      {
        id:4,
        name: 'Thai Chicken Soup',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['Thailand'],
        star: 5,
        imageUrl: '/assets/images/foods/food-4.jpg',
        tags:['Fastfood', 'Chicken', 'Soup', 'Thai', 'Lunch'],
      },
      {
        id:5,
        name: ' Spicy Chicken Fry',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['Bangladesh'],
        star: 3.5,
        imageUrl: '/assets/images/foods/food-5.jpg',
        tags:['Fastfood', 'Chicken', 'Spicy', 'Fry', 'Lunch'],
      },
      {
        id:6,
        name: 'Normal Chicken Fry',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['Bangladesh'],
        star: 5,
        imageUrl: '/assets/images/foods/food-6.jpg',
        tags:['Fastfood', 'Chicken', 'Fry', 'Lunch'],
      },
      {
        id:7,
        name: 'Chicken Kabab',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['India'],
        star: 5,
        imageUrl: '/assets/images/foods/food-7.jpg',
        tags:['Fastfood', 'Chicken', 'Kabab', 'Lunch'],
      },
      {
        id:8,
        name: 'Juice',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['Bangladesh'],
        star: 5,
        imageUrl: '/assets/images/foods/food-8.jpg',
        tags:['Fastfood', 'Juice', 'Lunch'],
      },
      {
        id:9,
        name: 'Chicken BBQ',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['USA'],
        star: 5,
        imageUrl: '/assets/images/foods/food-9.jpg',
        tags:['Fastfood', 'Chicken', 'BBQ', 'Lunch'],
      },
      {
        id:10,
        name: 'Small Shrimp Soup',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['Thailand'],
        star: 3.5,
        imageUrl: '/assets/images/foods/food-10.jpg',
        tags:['Fastfood', 'Lunch', 'Shrimp', 'Soup'],
      },
      {
        id:11,
        name: 'Crispy Chicken Fry ',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['China'],
        star: 3.5,
        imageUrl: '/assets/images/foods/food-11.jpg',
        tags:['Fastfood', 'Crispy', 'Chicken', 'Fry', 'Lunch'],
      },
    ]
  }
}
